__global_actions:
  import_configs:
    - views.view.faq
    - core.entity_view_display.node.faq.full
  install_modules:
    - openideal_faq_content
paragraphs.paragraphs_type.faq:
  expected_config:
    behavior_plugins:
      faq_view_behaviour:
        default_view: faqfield_accordion
  update_actions:
    change:
      behavior_plugins:
        faq_view_behaviour:
          default_view: faqfield_anchor_list
core.entity_view_display.node.faq.default:
  expected_config: {  }
  update_actions:
    add:
      content:
        field_faq_items:
          settings:
            limit: 0
            offset: 0
core.entity_view_display.paragraph.faq.default:
  expected_config:
    content:
      field_faq_items:
        settings:
          active: 0
          animate:
            duration: 200
            easing: linear
          collapsible: false
          event: click
          heightStyle: auto
        type: faqfield_accordion
        weight: 2
  update_actions:
    delete:
      content:
        field_faq_items:
          settings:
            active: 0
            animate:
              duration: 200
              easing: linear
            collapsible: false
            event: click
            heightStyle: auto
    change:
      content:
        field_faq_items:
          settings:
            anchor_list_type: ul
            limit: 0
            offset: 0
          type: faqfield_anchor_list
          weight: 3
